services:
  - docker

before_install:
  - docker pull supastuff/deploy:latest

script:
- |
  if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then \
      docker run -it -v $(pwd):/home/deploy/src \
                     -w /home/deploy/src \
                     supastuff/deploy:latest \
                     "packer validate pack.json && ansible-playbook provision.yml --check" \
  fi

- |
  if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then \
      docker run -it -v /var/run/docker.sock:/var/run/docker.sock \
                     --group-add $(getent group docker | cut -d: -f3) \
                     -e docker_user \
                     -e docker_pass \
                     -v $(pwd):/home/deploy/src \
                     -w /home/deploy/src \
                     supastuff/deploy:latest \
                     "packer build pack.json" \
  fi
